-- 코드를 입력하세요
SELECT
b.MEMBER_NAME AS MEMBER_NAME , a.REVIEW_TEXT AS REVIEW_TEXT , DATE_FORMAT(a.REVIEW_DATE, '%Y-%m-%d')  AS REVIEW_DATE 
FROM REST_REVIEW a 
LEFT JOIN MEMBER_PROFILE b
ON b.MEMBER_ID = a.MEMBER_ID 
WHERE b.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;