-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, (SUM(b.AMOUNT) * a.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT a 
LEFT JOIN FOOD_ORDER b ON a.PRODUCT_ID  = b.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5 
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC;