-- 코드를 입력하세요
# b.PUBLISHED_DATE  > 2020-01-10 00:00:00 > 데이터 타입 변경 필요  

SELECT b.BOOK_ID AS BOOK_ID, a.AUTHOR_NAME AS AUTHOR_NAME,
DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE 
FROM BOOK b JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;